from __future__ import annotations

from . import __version__
from .external_qm import selected_external_qm_script
from .keywords import (
    extra_value,
    normalize_key,
    uses_constraints,
)
from .mm import uses_mshake
from .models import ExternalQMCapabilities, RenderResult, SimulationSetup
from .release import TARGET_PQ_RELEASE
from .validation import (
    has_script_full_path,
    restart_filename,
    validate_input_file as validate_input_file,
    validate_setup,
)


_RUNNER_INPUT_NAMES = {
    "ase_dftbplus": "ase-dftbplus",
    "ase_xtb": "ase-xtb",
    "mace_mp": "mace",
    "mace_off": "mace_off",
}
# Advanced keywords the MM block writes in place; they are skipped in the
# trailing "additional settings" dump so no key appears twice.
_INLINE_EXTRA_KEYS = {"virial"}


def render_input(
    setup: SimulationSetup,
    *,
    external_qm: ExternalQMCapabilities | None = None,
) -> RenderResult:
    diagnostics = validate_setup(setup, external_qm=external_qm)
    if any(item.severity == "error" for item in diagnostics):
        return RenderResult(input_text="", diagnostics=diagnostics, valid=False)

    lines = _run_setup_lines(setup)
    lines.extend(_thermal_lines(setup))
    lines.extend(_pressure_lines(setup))
    lines.extend(_mm_lines(setup))
    lines.extend(_qm_lines(setup, external_qm))
    lines.extend(_extra_lines(setup))
    return RenderResult(
        input_text="\n".join(_annotate(lines)).rstrip() + "\n",
        diagnostics=diagnostics,
        valid=True,
    )


def _run_setup_lines(setup: SimulationSetup) -> list[str]:
    lines = [
        f"# Generated by PQSetup {__version__} for PQ {TARGET_PQ_RELEASE}",
        "",
        _section("dynamics"),
        f"jobtype = {setup.job_type};",
        f"nstep = {setup.steps};",
        f"timestep = {_number(setup.timestep_fs)};",
    ]
    lines.extend(
        [
            "",
            _section("files & continuation"),
            f"start_file = {setup.start_file};",
            f"restart_file = {restart_filename(setup)};",
            f"file_prefix = {setup.file_prefix};",
        ]
    )
    if setup.overwrite_output:
        lines.append("overwrite_output = on;")

    lines.extend(["", _section("initial state")])
    if setup.initialize_velocities or setup.ensemble in {"NVT", "NPT"}:
        lines.append(f"temp = {_number(setup.temperature_k)};")
    if setup.initialize_velocities:
        lines.append("init_velocities = true;")
    lines.append(f"random_seed = {setup.random_seed};")
    return lines


def _thermal_lines(setup: SimulationSetup) -> list[str]:
    lines: list[str] = []
    if setup.ensemble in {"NVT", "NPT"}:
        lines.extend(
            [
                "",
                _section("temperature coupling"),
                f"thermostat = {setup.thermostat};",
            ]
        )
        if setup.start_temperature_k is not None:
            lines.append(f"start_temp = {_number(setup.start_temperature_k)};")
            if setup.temperature_ramp_steps is not None:
                lines.append(f"temp_ramp_steps = {setup.temperature_ramp_steps};")
            lines.append(f"temp_ramp_frequency = {setup.temperature_ramp_frequency};")
        if (
            setup.thermostat in {"berendsen", "velocity_rescaling"}
            and setup.thermostat_relaxation_ps is not None
        ):
            lines.append(f"t_relaxation = {_number(setup.thermostat_relaxation_ps)};")
        elif setup.thermostat == "langevin":
            lines.append(f"friction = {_number(setup.thermostat_friction_ps_inverse)};")
        elif setup.thermostat == "nh-chain":
            lines.extend(
                [
                    f"nh-chain_length = {setup.nh_chain_length};",
                    "coupling_frequency = "
                    f"{_number(setup.coupling_frequency_cm_inverse)};",
                ]
            )
    return lines


def _pressure_lines(setup: SimulationSetup) -> list[str]:
    lines: list[str] = []
    if setup.ensemble == "NPT":
        lines.extend(
            [
                "",
                _section("pressure coupling"),
                f"manostat = {setup.manostat};",
                f"pressure = {_number(setup.pressure_bar)};",
            ]
        )
        if setup.manostat_relaxation_ps is not None:
            lines.append(f"p_relaxation = {_number(setup.manostat_relaxation_ps)};")
        lines.extend(
            [
                f"compressibility = {_number(setup.compressibility_bar_inverse)};",
                f"isotropy = {setup.pressure_isotropy};",
            ]
        )

    return lines


def _mm_lines(setup: SimulationSetup) -> list[str]:
    lines: list[str] = []
    if setup.job_type == "mm-md":
        lines.extend(
            [
                "",
                _section("molecular mechanics"),
            ]
        )
        if setup.density_g_cm3 is not None:
            lines.append(f"density = {_number(setup.density_g_cm3)};")
        virial = extra_value(setup, "virial") or "molecular"
        lines.extend(
            [
                f"rcoulomb = {_number(setup.coulomb_cutoff_angstrom)};",
                f"virial = {str(virial).strip().lower()};",
                f"force-field = {setup.mm_force_field};",
                "",
                _section("force-field files"),
                f"moldescriptor_file = {setup.moldescriptor_file};",
            ]
        )
        if setup.mm_force_field in {"off", "bonded"}:
            lines.append(f"guff_file = {setup.guff_file};")
        if setup.mm_force_field in {"on", "bonded"}:
            lines.extend(
                [
                    f"topology_file = {setup.topology_file};",
                    f"parameter_file = {setup.parameter_file};",
                ]
            )
        if setup.mm_force_field in {"bonded", "on"} and setup.intra_nonbonded_file:
            lines.append(f"intra-nonbonded_file = {setup.intra_nonbonded_file};")
        if (
            setup.mm_force_field in {"bonded", "on"}
            and uses_mshake(setup)
            and setup.mshake_file
        ):
            lines.append(f"mshake_file = {setup.mshake_file};")

    return lines


def _qm_lines(
    setup: SimulationSetup, external_qm: ExternalQMCapabilities | None
) -> list[str]:
    lines: list[str] = []
    if setup.job_type.startswith("qm-") and setup.runner:
        runner_name = _RUNNER_INPUT_NAMES.get(setup.runner, setup.runner)
        lines.extend(
            [
                "",
                _section("electronic structure"),
                f"qm_prog = {runner_name};",
            ]
        )
        runner_script, _ = selected_external_qm_script(
            setup.runner,
            setup.runner_script,
            external_qm,
        )
        # PQ treats qm_script and qm_script_full_path as mutually exclusive.
        if runner_script and not has_script_full_path(setup):
            lines.append(f"qm_script = {runner_script.name};")
        # Only when a descriptor is actually packed: naming one makes PQ
        # require the file, and it is not needed for NPT by itself.
        if setup.moldescriptor_file:
            lines.append(f"moldescriptor_file = {setup.moldescriptor_file};")
        if setup.runner == "dftbplus":
            lines.append(
                f"dftb_file = {setup.dftb_template_file or 'dftb_in.template'};"
            )
        if uses_constraints(setup) and setup.topology_file:
            lines.append(f"topology_file = {setup.topology_file};")
        if (
            setup.runner == "ase_xtb"
            and "xtb_method" not in setup.extra_settings
            and "xtb-method" not in setup.extra_settings
        ):
            lines.append("xtb_method = gfn2-xtb;")
        if setup.runner == "ase_dftbplus":
            if "slakos" not in setup.extra_settings:
                lines.append("slakos = 3ob;")
            if "dispersion" not in setup.extra_settings:
                lines.append("dispersion = on;")
    return lines


def _extra_lines(setup: SimulationSetup) -> list[str]:
    lines: list[str] = []
    additional = sorted(
        key
        for key in setup.extra_settings
        if not (setup.job_type == "mm-md" and normalize_key(key) in _INLINE_EXTRA_KEYS)
    )
    if additional:
        lines.extend(
            [
                "",
                _section("additional settings"),
            ]
        )
        for key in additional:
            lines.append(f"{key} = {_value(setup.extra_settings[key])};")
    return lines


NOTE_COLUMN = 30

# Keep physical units beside generated values; the PQ keywords stay plain text.
_NOTES = {
    "nstep": "steps",
    "timestep": "fs",
    "temp": "K",
    "start_temp": "K",
    "temp_ramp_steps": "steps",
    "temp_ramp_frequency": "steps",
    "t_relaxation": "ps",
    "friction": "ps⁻¹",
    "coupling_frequency": "cm⁻¹",
    "pressure": "bar",
    "p_relaxation": "ps",
    "compressibility": "bar⁻¹",
    "density": "g/cm³",
    "rcoulomb": "Å",
    "rnoncoulomb": "Å",
    "wolf_param": "Å⁻¹",
    "output_freq": "steps",
    "qm_loop_time_limit": "s",
}


def _annotate(lines: list[str]) -> list[str]:
    notes: list[str | None] = []
    for line in lines:
        key, separator, _ = line.partition(" = ")
        key = key.replace("-", "_").lower() if separator else ""
        notes.append(_NOTES.get(key))
    if not any(notes):
        return lines
    column = max(
        NOTE_COLUMN,
        max(len(line) for line, note in zip(lines, notes) if note) + 2,
    )
    return [
        f"{line:<{column}}# {note}" if note else line
        for line, note in zip(lines, notes)
    ]


def _section(title: str) -> str:
    return f"# {title.capitalize()}"


def _number(value: float | None) -> str:
    if value is None:
        raise ValueError("Missing numeric value.")
    return f"{value:.10g}"


def _value(value: str | int | float | bool) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)
